site_name: Manessia KB
site_url: https://kb.manessia.ch
site_description: Manessia Knowledge Base
site_author: Filek

# Repository
repo_name: manessia/manessia-kb
repo_url: https://github.com/manessia/manessia-kb/
edit_uri: ""

# Copyright
copyright: © 2018 Manessia Turicensis