site_name: Manessia KB
site_url: https://kb.manessia.ch
site_description: Manessia Knowledge Base
site_author: Filek

# Repository
repo_url: https://github.com/manessia/manessia-kb/

# Copyright
copyright: © 2018 Manessia Turicensis

# Configuration
theme:
  name: 'material'
  feature:
    tabs: true
  language: 'de'